### ISSUE TITLE
fix: OnCompleted stops dialogues working in FluentInputFile

### ISSUE THREAD

**Issue by ApacheTech** [microsoft/fluentui-blazor#3355]
# 🐛 Bug Report

If you try to use dialogues within the `OnCompleted` task of a `FluentInputFile` component, the buttons within the dialogue do not respond.

## 💻 Repro or Code Sample

This assumes that `<FluentDialogProvider />` is added within `MainLayout.razor` or `App.razor`.

```cs
@page "/sandbox"

<h3>
    @_message
</h3>

<FluentStack HorizontalGap="4">
    <FluentButton OnClick="ShowConfirmationAsync" Appearance="Appearance.Accent">
        Show Confirmation Directly
    </FluentButton>
    <FluentButton Id="btnUpload" Appearance="Appearance.Accent">
        Upload Then Confirm
    </FluentButton>
</FluentStack>

<FluentInputFile Class="h-fit w-full"
                 Multiple="false"
                 AnchorId="btnUpload"
                 Mode="InputFileMode.Stream"
                 MaximumFileSize="@(1024 * 1024 * 1024)"
                 DragDropZoneVisible="false"
                 OnCompleted="OnFileUploadedAsync" />

@code {
    private string _message = "Ready.";

    [Inject]
    private IDialogService Dialogue { get; init; }

    private async Task OnFileUploadedAsync(IEnumerable<FluentInputFileEventArgs> args)
    {
        await ShowConfirmationAsync();
    }

    private async Task ShowConfirmationAsync()
    {
        var dialogue = await Dialogue.ShowConfirmationAsync("Do you want to continue?");
        var result = await dialogue.Result;
        _message = result.Cancelled
            ? "Cancelled"
            : "Accepted";
    }
}

```

## 🤔 Expected Behavior

Whether the confirmation dialogue is shown via `OnClick` from `FluentButton`, or `OnComplete` from `FluentInputFile`, both should allow the dialogue to be responsive.

## 😯 Current Behavior

The above code sample shows that the buttons within the dialogue are unresponsive, if called via the `OnCompleted` task.

## 💁 Possible Solution

Could the `OnCompleted` task be detached from the page dispatcher, requiring an `InvokeAsync` wrapper to reattach it?

## 🔦 Context

One of our services is Partially Automated Workflows, where the user uploads a file, and needs to confirm that they wish to continue if there are any chargable items within the workflow. This issue stops that process from working.

## 🌍 Your Environment

* OS & Device: Windows 11 Enterprise
* Browser: Tested on Firefox, Edge, Opera, Chrome, and Maxathon
* Framework Version: net8.0
* Blazor App: Global InteractiveServer
* Fluent UI Blazor library Version: 4.11.4

**Comment by ApacheTech** [comment]
Yes please. It's causing a lot of issues.

**Comment by rpodevns** [comment]
@dvoituron @vnbaaij Should I create the PR or paste the updated code here?  Just not sure of the approval process for PRs.

**Comment by vnbaaij** [comment]
Create a PR please. Reference this issue with 'Fix #3355' in the description (not in the title). Denis or I will then take a look and  if everything checks out, we'll merge it in.

**Comment by rpodevns** [comment]
@vnbaaij Thanks. I wasn’t sure when to proceed with the PR. I wanted to confirm since what I see as an issue might not always be one.

The fix is a substantial change in how streamed uploads are done.  Should there be an opt-in parameter and what should it be named?

**Comment by vnbaaij** [comment]
Is there any change needed to the code a developer uses? If so, yes then we need to make it opt-in. If not, then we can change whatever we want.

**Comment by ApacheTech** [comment]
Even if it doesn't change the public API layer, it will yield back to the dispatcher, causing different side-effects than it currently does. Everyone is currently using it synchronously, and so to yield back control will be a significant change to how it is used, even if it is supposed to fix the problems.

Could it be a new mode? `AsychronousStream`

That way, no current code is touched, and people can opt-in by choosing the new upload mode. Then, there's no options to set, and you don't need to worry about individual overrides, or other side-effects.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by vnbaaij** [comment]
I'm ok with creating a new mode or opt-in.

**Comment by rpodevns** [comment]
@ApacheTech  I'm re-thinking how I've approached this. In the meantime, have a look at:  https://github.com/microsoft/fluentui-blazor/issues/2592

**Comment by ApacheTech** [comment]
@rpodevns Has there been any further developments on a fix for this?

**Comment by ApacheTech** [comment]
@rpodevns, it's been over three weeks now since there's been any update for this. Will a fix be coming any time soon?

**Comment by ApacheTech** [comment]
@rpodevns Can I please have an update? Are you still working on this?

**Comment by ApacheTech** [comment]
@dvoituron @vnbaaij It looks like the person who was going to make a fix for this has gone MIA. There's been no word since Feb.

**Comment by MarvinKlein1508** [comment]
I've tried replicating this and copied the code from above into the demo projects. And for me this works just fine in both Server and WebAssembly. 

I've tried it in Chrome, Edge and Firefox. And everytime I was able to click each button in the dialog and the result will be displayed for me. Perhaps this has been fixed already with another PR?

**Comment by ApacheTech** [comment]
I've update to 4.11.8, and the problem still exists.

**Comment by vnbaaij** [comment]
@ApacheTech can you then please share a repo with which we can replicate. Going with what @MarvinKlein1508 found, the reproduction code is not... reproducing the issue.

**Comment by ApacheTech** [comment]
It will take me a while. All of our source code is closed source. I'll have to create a project specifically for this.

**Comment by ApacheTech** [comment]
This is still not working with files over 64KB.

https://github.com/ApacheTech/FluentUiSandbox

Works with 64KB: [Test File 2979.txt](https://github.com/user-attachments/files/19960925/Test.File.2979.txt)
Does not work with 65KB: [Test File 2980.txt](https://github.com/user-attachments/files/19960929/Test.File.2980.txt)

**Comment by MarvinKlein1508** [comment]
I can indeed reproduce this in the demo project as well when I try to upload a file larger than 64KB.

@vnbaaij what even is the point of uploading files via a stream here? What's the use case for this and why would I choose `Stream` over `Buffer`?

```cs
case InputFileMode.Stream:

                    var fileSizePart1 = file.Size / 2;
                    var fileSizePart2 = file.Size - fileSizePart1;

                    // Get a reference to the current file Stream
                    fileDetails.Stream = file.OpenReadStream(MaximumFileSize);

                    // Progression percent (first 50%)
                    totalRead += fileSizePart1;
                    await UpdateProgressAsync(totalRead, totalFileSizes, title);

                    // Uploaded event
                    if (OnFileUploaded.HasDelegate)
                    {
                        fileDetails.ProgressPercent = ProgressPercent;
                        await OnFileUploaded.InvokeAsync(fileDetails);
                    }

                    // Progression percent (last 50%)
                    totalRead += fileSizePart2;
                    await UpdateProgressAsync(totalRead, totalFileSizes, title);

                    break;

```

And why is the source code "faking" the upload in two 50% chunks?

**Comment by vnbaaij** [comment]
@dvoituron might be able to answer that. It is mostly code coming from him.

**Comment by MarvinKlein1508** [comment]
@dvoituron the docs also don't specify when you should use `Stream` mode.

![Image](https://github.com/user-attachments/assets/b2c6671a-2d6e-47d0-8843-dd36ef69dd94)

**Comment by dvoituron** [comment]
You have 3 modes:
- **SaveToTemporaryFolder** if you have the possibility to create a local file (not always possible, depending on the user rights in the host).
- **Buffer** if the files are not too large because you will have the entire contents of the file in memory, at the end of the file transfer.
- **Stream** if you want to receive the files in small blocks per small blocks. So, no local file and no extra memory usage.

**Comment by MarvinKlein1508** [comment]
@dvoituron so basically `Stream` should be used for large files. What do you consider as large? 10MB or 100MB or 1GB?

Can you also clarify why you are simulating the upload with two 50% update events?

**Comment by dvoituron** [comment]
> [@dvoituron](https://github.com/dvoituron) so basically `Stream` should be used for large files. What do you consider as large? 10MB or 100MB or 1GB?

A "large" file depends on your server capacity :-) So it's depend of your choices.
if you can accept 1GB of bytes in memory during a small time (during the file transfer), a large file is bigger :-)

> Can you also clarify why you are simulating the upload with two 50% update events?

It's just to trigger the `ProgressPercentChanged` event: 50%, 100% (this is not possible to have more details using `OpenReadStream`)

**Comment by MarvinKlein1508** [comment]
@dvoituron ah I get it. So basically if you are using `Stream` then you'll need to handle this by yourself. 



@ApacheTech I got your code to working by changing it to this:
```cs
private async Task OnFileUploadedAsync(IEnumerable<FluentInputFileEventArgs> args)
{
    foreach (var item in args)
    {
        if (item.Stream is not null)
        {
            await using MemoryStream fs = new();
            await item.Stream.CopyToAsync(fs);
            await item.Stream.DisposeAsync();
            await ShowConfirmationAsync();
        }
    }   
}
```

Depending on your use-case you'll probably use `FileStream` instead as there is no real benefit in using `MemoryStream` here. If I understand the implementation correctly then you could better use `Buffer` as this results in the same behaviour only with a correct output of the current upload state.

Of course you may need to adapt your code to stop the upload progress when you manually cancel it. I guess you need to dispose all streams at least.

**Comment by MarvinKlein1508** [comment]
@dvoituron is `ProgressPercentChanged` being triggered just for fancyness or does it need to be raised in order for the component to work correctly?

**Comment by MarvinKlein1508** [comment]
@dvoituron if my explanation above is correct then I will create a PR to explain this mode in the docs.

**Comment by dvoituron** [comment]
> [@dvoituron](https://github.com/dvoituron) ah I get it. So basically if you are using `Stream` then you'll need to handle this by yourself.

Exact.

This `Stream` mode returns the default Blazor [IBrowserFile.OpenReadStream](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.forms.ibrowserfile.openreadstream).
In this mode, you "manage" the stream as you like.

And so, the `ProgressPercentChanged` event is just for information (in other cases too, but more related to the real content).

I await your PR with impatience. Additional explanations, in the context of the Stream example, would probably be useful. :-)

**Comment by dvoituron** [comment]
> [@dvoituron](https://github.com/dvoituron) if my explanation above is correct then I will create a PR to explain this mode in the docs.

You will find a little extra information in the v5 documentation :-)
https://fluentui-blazor-v5.azurewebsites.net/InputFile#mode-inputfilemode.stream

**Comment by MarvinKlein1508** [comment]
@dvoituron This is my suggestion (might contain grammar or spelling mistakes)

![Image](https://github.com/user-attachments/assets/2dd625f7-2e36-41ee-83d5-01ec3e756564)

![Image](https://github.com/user-attachments/assets/ec8953d1-c02b-4591-86de-5ee6eb90bb69)

**Comment by dvoituron** [comment]
Seems good

**Comment by MarvinKlein1508** [comment]
Alright PR is up. I guess you can close this issue here then as this seems to be working fine.
